# Minimal Snakefile so `snakemake site` works now
configfile: "config/config.yaml"

include: "workflow/rules/fetch.smk"
include: "workflow/rules/qc_align.smk"
include: "workflow/rules/release.smk"
include: "workflow/rules/align_tree.smk"

rule all:
    input:
        # fetch/normalize/link table (nice for debugging)
        expand("data/staging/{locus}.gb", locus=config.get("backbone_loci", []) + ["ITS"]),
        "data/staging/specimens/specimen_loci.tsv",
        "data/staging/loci_table.tsv",
	"data/trees/backbone.treefile",
        "site"
